// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Decision struct {
	ID      int64
	NameID  int64
	Approve bool
	User    pgtype.Text
}

type Name struct {
	ID       int64
	Name     pgtype.Text
	IsFemale pgtype.Bool
}

type Popularity struct {
	ID          int64
	NameID      int64
	Nationality pgtype.Text
	Value       pgtype.Int4
}

type SchemaMigration struct {
	Version string
}
