// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
)

const getName = `-- name: GetName :one
SELECT id, name, is_female
FROM names
WHERE id = $1
`

func (q *Queries) GetName(ctx context.Context, id int64) (Name, error) {
	row := q.db.QueryRow(ctx, getName, id)
	var i Name
	err := row.Scan(&i.ID, &i.Name, &i.IsFemale)
	return i, err
}
